/**
 * Eight synthetic personas for the LLM Taste-Expansion Audit.
 *
 * Covers the matrix: mainstream vs niche, rich history vs cold start,
 * Western-centric vs not, single-genre vs eclectic.
 */
import type { PersonaDefinition } from './types';

function makeId(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

// ──────────────────────────────────────────────────────────────────────
// Persona 1 — Mainstream pop, rich history
// ──────────────────────────────────────────────────────────────────────
const p1: PersonaDefinition = {
  id: makeId('mainstream-pop'),
  label: 'Mainstream Pop',
  description:
    'Years of Top 40/chart pop listening, high play counts, clear centroid.',
  homeTerritory: {
    genres: ['pop', 'dance pop', 'synthpop', 'electropop'],
    primaryGenre: 'pop',
    country: 'US',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Taylor Swift', genres: ['pop', 'country pop'], popularity: 100 },
    { name: 'Dua Lipa', genres: ['pop', 'dance pop'], popularity: 95 },
    { name: 'The Weeknd', genres: ['pop', 'rnb'], popularity: 96 },
    { name: 'Ed Sheeran', genres: ['pop', 'singer-songwriter'], popularity: 97 },
    { name: 'Billie Eilish', genres: ['pop', 'electropop'], popularity: 94 },
  ],
  exploredArtists: [
    { id: 'taylor-swift', name: 'Taylor Swift', genres: ['pop', 'country pop'], popularity: 100, weight: 0.95 },
    { id: 'dua-lipa', name: 'Dua Lipa', genres: ['pop', 'dance pop'], popularity: 95, weight: 0.88 },
    { id: 'the-weeknd', name: 'The Weeknd', genres: ['pop', 'rnb'], popularity: 96, weight: 0.9 },
    { id: 'ed-sheeran', name: 'Ed Sheeran', genres: ['pop', 'singer-songwriter'], popularity: 97, weight: 0.85 },
    { id: 'billie-eilish', name: 'Billie Eilish', genres: ['pop', 'electropop'], popularity: 94, weight: 0.82 },
    { id: 'ariana-grande', name: 'Ariana Grande', genres: ['pop', 'dance pop'], popularity: 96, weight: 0.8 },
    { id: 'bruno-mars', name: 'Bruno Mars', genres: ['pop', 'funk pop'], popularity: 93, weight: 0.78 },
    { id: 'charli-xcx', name: 'Charli XCX', genres: ['pop', 'synthpop', 'hyperpop'], popularity: 91, weight: 0.72 },
    { id: 'lizzo', name: 'Lizzo', genres: ['pop', 'funk pop'], popularity: 88, weight: 0.7 },
    { id: 'post-malone', name: 'Post Malone', genres: ['pop', 'hip hop'], popularity: 92, weight: 0.75 },
    { id: 'harry-styles', name: 'Harry Styles', genres: ['pop', 'rock'], popularity: 93, weight: 0.73 },
    { id: 'olivia-rodrigo', name: 'Olivia Rodrigo', genres: ['pop', 'pop rock'], popularity: 94, weight: 0.77 },
    { id: 'doja-cat', name: 'Doja Cat', genres: ['pop', 'hip hop'], popularity: 91, weight: 0.71 },
    { id: 'sza', name: 'SZA', genres: ['pop', 'rnb'], popularity: 93, weight: 0.76 },
    { id: 'lana-del-rey', name: 'Lana Del Rey', genres: ['pop', 'indie pop'], popularity: 90, weight: 0.68 },
    { id: 'tyler-the-creator', name: 'Tyler, the Creator', genres: ['hip hop', 'pop', 'neo-soul'], popularity: 89, weight: 0.65 },
    { id: 'khalid', name: 'Khalid', genres: ['pop', 'rnb'], popularity: 87, weight: 0.63 },
    { id: 'marshmello', name: 'Marshmello', genres: ['pop', 'edm'], popularity: 88, weight: 0.6 },
    { id: 'coldplay', name: 'Coldplay', genres: ['pop', 'alternative rock'], popularity: 92, weight: 0.7 },
    { id: 'imagine-dragons', name: 'Imagine Dragons', genres: ['pop', 'alternative rock'], popularity: 90, weight: 0.65 },
    { id: 'maroon-5', name: 'Maroon 5', genres: ['pop', 'funk pop'], popularity: 91, weight: 0.62 },
    { id: 'katy-perry', name: 'Katy Perry', genres: ['pop', 'dance pop'], popularity: 89, weight: 0.58 },
    { id: 'shawn-mendes', name: 'Shawn Mendes', genres: ['pop', 'singer-songwriter'], popularity: 88, weight: 0.56 },
    { id: 'camila-cabello', name: 'Camila Cabello', genres: ['pop', 'dance pop'], popularity: 86, weight: 0.54 },
    { id: 'megan-trainor', name: 'Meghan Trainor', genres: ['pop', 'doo-wop pop'], popularity: 84, weight: 0.5 },
    { id: 'niall-horan', name: 'Niall Horan', genres: ['pop', 'singer-songwriter'], popularity: 83, weight: 0.48 },
    { id: 'louis-tomlinson', name: 'Louis Tomlinson', genres: ['pop', 'indie pop'], popularity: 82, weight: 0.46 },
    { id: 'selena-gomez', name: 'Selena Gomez', genres: ['pop', 'dance pop'], popularity: 87, weight: 0.55 },
    { id: 'avicii', name: 'Avicii', genres: ['edm', 'pop'], popularity: 88, weight: 0.6 },
    { id: 'calvin-harris', name: 'Calvin Harris', genres: ['edm', 'pop'], popularity: 89, weight: 0.62 },
    { id: 'lady-gaga', name: 'Lady Gaga', genres: ['pop', 'dance pop'], popularity: 92, weight: 0.7 },
    { id: 'pink', name: 'P!nk', genres: ['pop', 'pop rock'], popularity: 88, weight: 0.58 },
    { id: 'adele', name: 'Adele', genres: ['pop', 'soul'], popularity: 94, weight: 0.78 },
    { id: 'rihanna', name: 'Rihanna', genres: ['pop', 'rnb', 'dance pop'], popularity: 96, weight: 0.82 },
    { id: 'beyonce', name: 'Beyonce', genres: ['pop', 'rnb'], popularity: 98, weight: 0.88 },
    { id: 'justin-timberlake', name: 'Justin Timberlake', genres: ['pop', 'rnb'], popularity: 90, weight: 0.65 },
    { id: 'kehlani', name: 'Kehlani', genres: ['pop', 'rnb'], popularity: 82, weight: 0.48 },
    { id: 'sabrina-carpenter', name: 'Sabrina Carpenter', genres: ['pop', 'dance pop'], popularity: 90, weight: 0.7 },
    { id: 'chappell-roan', name: 'Chappell Roan', genres: ['pop', 'synthpop'], popularity: 88, weight: 0.68 },
    { id: 'gracie-abrams', name: 'Gracie Abrams', genres: ['pop', 'singer-songwriter'], popularity: 85, weight: 0.55 },
    { id: 'tate-mcrae', name: 'Tate McRae', genres: ['pop', 'dance pop'], popularity: 87, weight: 0.58 },
    { id: 'noah-kahan', name: 'Noah Kahan', genres: ['pop', 'folk pop'], popularity: 86, weight: 0.52 },
    { id: 'morgan-wallen', name: 'Morgan Wallen', genres: ['country pop', 'pop'], popularity: 90, weight: 0.6 },
    { id: 'jungkook', name: 'Jung Kook', genres: ['pop', 'k-pop'], popularity: 95, weight: 0.8 },
    { id: 'ice-spice', name: 'Ice Spice', genres: ['pop', 'rap'], popularity: 85, weight: 0.5 },
    { id: 'travis-scott', name: 'Travis Scott', genres: ['hip hop', 'pop rap'], popularity: 92, weight: 0.72 },
    { id: 'bad-bunny', name: 'Bad Bunny', genres: ['reggaeton', 'latin pop'], popularity: 96, weight: 0.78 },
    { id: 'daddy-yankee', name: 'Daddy Yankee', genres: ['reggaeton', 'latin pop'], popularity: 90, weight: 0.55 },
    { id: 'j-balvin', name: 'J Balvin', genres: ['reggaeton', 'latin pop'], popularity: 91, weight: 0.58 },
    { id: 'ozuna', name: 'Ozuna', genres: ['reggaeton', 'latin pop'], popularity: 89, weight: 0.52 },
    { id: 'karol-g', name: 'Karol G', genres: ['reggaeton', 'latin pop'], popularity: 93, weight: 0.65 },
    { id: 'bebe-rexha', name: 'Bebe Rexha', genres: ['pop', 'dance pop'], popularity: 86, weight: 0.48 },
    { id: 'zara-larsson', name: 'Zara Larsson', genres: ['pop', 'dance pop'], popularity: 84, weight: 0.46 },
    { id: 'roxette', name: 'Roxette', genres: ['pop', 'pop rock'], popularity: 78, weight: 0.35 },
    { id: 'whitney-houston', name: 'Whitney Houston', genres: ['pop', 'soul'], popularity: 90, weight: 0.55 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['pop', 'dance pop', 'synthpop'],
    longTermGenres: ['pop', 'dance pop', 'electropop', 'rnb'],
    driftScore: 0.1,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 2 — Niche/underground: UK dubstep
// ──────────────────────────────────────────────────────────────────────
const p2: PersonaDefinition = {
  id: makeId('uk-dubstep'),
  label: 'UK Dubstep',
  description:
    'Deep in UK dubstep scene. Small but very consistent listening pattern.',
  homeTerritory: {
    genres: ['dubstep', 'grime', 'uk garage', 'bass music'],
    primaryGenre: 'dubstep',
    country: 'GB',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Burial', genres: ['dubstep', 'ambient', 'garage'], popularity: 72 },
    { name: 'Skream', genres: ['dubstep', 'uk garage'], popularity: 65 },
    { name: 'Benga', genres: ['dubstep', 'bass music'], popularity: 58 },
    { name: 'Mala', genres: ['dubstep', 'dub'], popularity: 55 },
    { name: 'Coki', genres: ['dubstep', 'bass music'], popularity: 52 },
  ],
  exploredArtists: [
    { id: 'burial', name: 'Burial', genres: ['dubstep', 'ambient', 'garage'], popularity: 72, weight: 0.95 },
    { id: 'skream', name: 'Skream', genres: ['dubstep', 'uk garage'], popularity: 65, weight: 0.9 },
    { id: 'benga', name: 'Benga', genres: ['dubstep', 'bass music'], popularity: 58, weight: 0.85 },
    { id: 'mala', name: 'Mala', genres: ['dubstep', 'dub'], popularity: 55, weight: 0.88 },
    { id: 'coki', name: 'Coki', genres: ['dubstep', 'bass music'], popularity: 52, weight: 0.82 },
    { id: 'digital-mystikz', name: 'Digital Mystikz', genres: ['dubstep', 'dub'], popularity: 50, weight: 0.8 },
    { id: 'loefah', name: 'Loefah', genres: ['dubstep', 'bass music'], popularity: 48, weight: 0.78 },
    { id: 'dbridge', name: 'dBridge', genres: ['dubstep', 'drum and bass', 'autonomic'], popularity: 55, weight: 0.75 },
    { id: 'pinch', name: 'Pinch', genres: ['dubstep', 'bass music'], popularity: 47, weight: 0.72 },
    { id: ' hatcha', name: 'Hatcha', genres: ['dubstep', 'bass music'], popularity: 44, weight: 0.7 },
    { id: 'youngsta', name: 'Youngsta', genres: ['dubstep', 'bass music'], popularity: 42, weight: 0.68 },
    { id: 'n-type', name: 'N-Type', genres: ['dubstep', 'bass music'], popularity: 43, weight: 0.66 },
    { id: 'kode9', name: 'Kode9', genres: ['dubstep', 'bass music'], popularity: 55, weight: 0.78 },
    { id: 'spaceape', name: 'Spaceape', genres: ['dubstep', 'dub'], popularity: 45, weight: 0.72 },
    { id: 'la-rika', name: 'La-Rika', genres: ['dubstep', 'bass music'], popularity: 38, weight: 0.6 },
    { id: 'benton', name: 'Benton', genres: ['dubstep', 'bass music'], popularity: 40, weight: 0.62 },
    { id: 'commodo', name: 'Commodo', genres: ['dubstep', 'bass music'], popularity: 42, weight: 0.65 },
    { id: 'ahnu', name: 'Ahnu', genres: ['dubstep', 'ambient'], popularity: 35, weight: 0.58 },
    { id: 'ihon', name: 'Ihon', genres: ['dubstep', 'bass music'], popularity: 34, weight: 0.55 },
    { id: 'sultan', name: 'Sultan', genres: ['dubstep', 'uk garage'], popularity: 40, weight: 0.6 },
    { id: 'mr-tea', name: 'Mr. Tea', genres: ['dubstep', 'bass music'], popularity: 36, weight: 0.52 },
    { id: 'wayfarer', name: 'Wayfarer', genres: ['dubstep', 'ambient dub'], popularity: 38, weight: 0.55 },
    { id: 'sines', name: 'Sines', genres: ['dubstep', 'bass music'], popularity: 33, weight: 0.5 },
    { id: 'kryptic-minds', name: 'Kryptic Minds', genres: ['dubstep', 'ambient'], popularity: 40, weight: 0.58 },
    { id: 'billy-nasty', name: 'Billy Nasty', genres: ['techno', 'dubstep'], popularity: 45, weight: 0.5 },
    { id: 'boddika', name: 'Boddika', genres: ['techno', 'bass music'], popularity: 50, weight: 0.52 },
    { id: 'joy-orbison', name: 'Joy Orbison', genres: ['uk garage', 'house'], popularity: 55, weight: 0.6 },
    { id: 'four-tet', name: 'Four Tet', genres: ['electronic', 'ambient'], popularity: 72, weight: 0.65 },
    { id: 'burial-adj-1', name: 'Volor Flex', genres: ['dubstep', 'ambient'], popularity: 35, weight: 0.55 },
    { id: 'burial-adj-2', name: 'Zomby', genres: ['dubstep', 'electronic'], popularity: 50, weight: 0.52 },
    { id: 'deep-medi-1', name: 'SP:MC', genres: ['dubstep', 'bass music'], popularity: 38, weight: 0.5 },
    { id: 'deep-medi-2', name: 'J:Kenzo', genres: ['dubstep', 'bass music'], popularity: 42, weight: 0.55 },
    { id: 'tempa-1', name: 'Distance', genres: ['dubstep', 'bass music'], popularity: 45, weight: 0.58 },
    { id: 'tempa-2', name: 'Cyrus', genres: ['dubstep', 'bass music'], popularity: 40, weight: 0.52 },
    { id: 'sub-rnt-1', name: 'Tunnidge', genres: ['dubstep', 'bass music'], popularity: 38, weight: 0.5 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['dubstep', 'bass music', 'ambient'],
    longTermGenres: ['dubstep', 'grime', 'uk garage', 'bass music'],
    driftScore: 0.05,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 3 — Eclectic, rich history
// ──────────────────────────────────────────────────────────────────────
const p3: PersonaDefinition = {
  id: makeId('eclectic'),
  label: 'Eclectic',
  description:
    'Genuinely spread across 5+ unrelated genres, no single dominant territory.',
  homeTerritory: {
    genres: ['jazz', 'metal', 'k-pop', 'ambient', 'reggaeton', 'country'],
    primaryGenre: 'jazz',
    country: 'US',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Miles Davis', genres: ['jazz', 'bebop'], popularity: 82 },
    { name: 'Metallica', genres: ['metal', 'thrash metal'], popularity: 88 },
    { name: 'BTS', genres: ['k-pop', 'pop'], popularity: 95 },
    { name: 'Brian Eno', genres: ['ambient', 'electronic'], popularity: 75 },
    { name: 'Bad Bunny', genres: ['reggaeton', 'latin pop'], popularity: 96 },
  ],
  exploredArtists: [
    { id: 'miles-davis', name: 'Miles Davis', genres: ['jazz', 'bebop'], popularity: 82, weight: 0.9 },
    { id: 'metallica', name: 'Metallica', genres: ['metal', 'thrash metal'], popularity: 88, weight: 0.85 },
    { id: 'bts', name: 'BTS', genres: ['k-pop', 'pop'], popularity: 95, weight: 0.88 },
    { id: 'brian-eno', name: 'Brian Eno', genres: ['ambient', 'electronic'], popularity: 75, weight: 0.82 },
    { id: 'bad-bunny', name: 'Bad Bunny', genres: ['reggaeton', 'latin pop'], popularity: 96, weight: 0.8 },
    { id: 'john-coltrane', name: 'John Coltrane', genres: ['jazz', 'free jazz'], popularity: 78, weight: 0.75 },
    { id: 'slayer', name: 'Slayer', genres: ['metal', 'thrash metal'], popularity: 78, weight: 0.7 },
    { id: 'blackpink', name: 'BLACKPINK', genres: ['k-pop', 'pop'], popularity: 92, weight: 0.72 },
    { id: 'aphex-twin', name: 'Aphex Twin', genres: ['electronic', 'ambient', 'IDM'], popularity: 72, weight: 0.7 },
    { id: 'dolly-parton', name: 'Dolly Parton', genres: ['country', 'country pop'], popularity: 85, weight: 0.65 },
    { id: 'thelonious-monk', name: 'Thelonious Monk', genres: ['jazz', 'bebop'], popularity: 70, weight: 0.68 },
    { id: 'iron-maiden', name: 'Iron Maiden', genres: ['metal', 'heavy metal'], popularity: 85, weight: 0.7 },
    { id: 'stray-kids', name: 'Stray Kids', genres: ['k-pop'], popularity: 90, weight: 0.65 },
    { id: ' Boards of Canada', name: 'Boards of Canada', genres: ['electronic', 'ambient'], popularity: 68, weight: 0.62 },
    { id: 'jbalvin', name: 'J Balvin', genres: ['reggaeton', 'latin pop'], popularity: 91, weight: 0.6 },
    { id: 'willie-nelson', name: 'Willie Nelson', genres: ['country', 'outlaw country'], popularity: 80, weight: 0.55 },
    { id: 'herbie-hancock', name: 'Herbie Hancock', genres: ['jazz', 'funk'], popularity: 75, weight: 0.65 },
    { id: 'megadeth', name: 'Megadeth', genres: ['metal', 'thrash metal'], popularity: 80, weight: 0.6 },
    { id: 'twice', name: 'TWICE', genres: ['k-pop', 'pop'], popularity: 88, weight: 0.58 },
    { id: 'stars-of-the-lid', name: 'Stars of the Lid', genres: ['ambient', 'drone'], popularity: 55, weight: 0.52 },
    { id: 'karol-g', name: 'Karol G', genres: ['reggaeton', 'latin pop'], popularity: 93, weight: 0.55 },
    { id: 'hank-williams', name: 'Hank Williams', genres: ['country', 'honky tonk'], popularity: 78, weight: 0.48 },
    { id: 'pharoah-sanders', name: 'Pharoah Sanders', genres: ['jazz', 'spiritual jazz'], popularity: 65, weight: 0.6 },
    { id: 'meshuggah', name: 'Meshuggah', genres: ['metal', 'progressive metal'], popularity: 68, weight: 0.55 },
    { id: 'aespa', name: 'aespa', genres: ['k-pop'], popularity: 85, weight: 0.52 },
    { id: 'halo', name: 'Halo', genres: ['ambient', 'electronic'], popularity: 52, weight: 0.48 },
    { id: 'ozuna', name: 'Ozuna', genres: ['reggaeton', 'latin pop'], popularity: 89, weight: 0.5 },
    { id: 'johnny-cash', name: 'Johnny Cash', genres: ['country', 'outlaw country'], popularity: 85, weight: 0.52 },
    { id: 'chick-corea', name: 'Chick Corea', genres: ['jazz', 'fusion'], popularity: 70, weight: 0.55 },
    { id: 'opeth', name: 'Opeth', genres: ['metal', 'progressive metal'], popularity: 65, weight: 0.5 },
    { id: 'newjeans', name: 'NewJeans', genres: ['k-pop', 'pop'], popularity: 88, weight: 0.52 },
    { id: 'tim-hecker', name: 'Tim Hecker', genres: ['ambient', 'drone'], popularity: 50, weight: 0.45 },
    { id: 'nicky-jam', name: 'Nicky Jam', genres: ['reggaeton', 'latin pop'], popularity: 85, weight: 0.48 },
    { id: 'george-strait', name: 'George Strait', genres: ['country'], popularity: 82, weight: 0.45 },
    { id: 'kamasi-washington', name: 'Kamasi Washington', genres: ['jazz', 'spiritual jazz'], popularity: 65, weight: 0.58 },
    { id: 'gojira', name: 'Gojira', genres: ['metal', 'progressive metal'], popularity: 68, weight: 0.52 },
    { id: 'le-sserafim', name: 'LE SSERAFIM', genres: ['k-pop'], popularity: 85, weight: 0.48 },
    { id: 'gas', name: 'Gas', genres: ['ambient', 'electronic'], popularity: 48, weight: 0.42 },
    { id: 'maluma', name: 'Maluma', genres: ['reggaeton', 'latin pop'], popularity: 88, weight: 0.5 },
    { id: 'kacey-musgraves', name: 'Kacey Musgraves', genres: ['country', 'pop'], popularity: 82, weight: 0.52 },
    { id: 'cecil-taylor', name: 'Cecil Taylor', genres: ['jazz', 'free jazz'], popularity: 55, weight: 0.45 },
    { id: 'between-the-buried', name: 'Between the Buried and Me', genres: ['metal', 'progressive metal'], popularity: 58, weight: 0.42 },
    { id: 'ive', name: 'IVE', genres: ['k-pop'], popularity: 85, weight: 0.48 },
    { id: 'grouper', name: 'Grouper', genres: ['ambient', 'dream pop'], popularity: 55, weight: 0.45 },
    { id: 'sech', name: 'Sech', genres: ['reggaeton', 'latin pop'], popularity: 82, weight: 0.45 },
    { id: 'sturgill-simpson', name: 'Sturgill Simpson', genres: ['country', 'outlaw country'], popularity: 70, weight: 0.42 },
    { id: 'sonny-rollins', name: 'Sonny Rollins', genres: ['jazz'], popularity: 65, weight: 0.4 },
    { id: 'dream-theater', name: 'Dream Theater', genres: ['metal', 'progressive metal'], popularity: 72, weight: 0.45 },
    { id: 'ateez', name: 'ATEEZ', genres: ['k-pop'], popularity: 82, weight: 0.45 },
    { id: 'william-basinski', name: 'William Basinski', genres: ['ambient', 'drone'], popularity: 45, weight: 0.38 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['jazz', 'k-pop', 'ambient'],
    longTermGenres: ['jazz', 'metal', 'k-pop', 'ambient', 'reggaeton', 'country'],
    driftScore: 0.4,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 4 — Cold start, stated preference only
// ──────────────────────────────────────────────────────────────────────
const p4: PersonaDefinition = {
  id: makeId('cold-start'),
  label: 'Cold Start',
  description:
    'No listening history, just a handful of self-selected favorites at onboarding.',
  homeTerritory: {
    genres: ['folk', 'indie rock'],
    primaryGenre: 'folk',
    country: 'US',
  },
  coldStart: true,
  seedArtists: [
    { name: 'Bon Iver', genres: ['folk', 'indie folk'], popularity: 78 },
    { name: 'Phoebe Bridgers', genres: ['indie rock', 'indie folk'], popularity: 82 },
    { name: 'Fleet Foxes', genres: ['indie folk', 'folk'], popularity: 72 },
  ],
  exploredArtists: [
    { id: 'bon-iver', name: 'Bon Iver', genres: ['folk', 'indie folk'], popularity: 78, weight: 0.8 },
    { id: 'phoebe-bridgers', name: 'Phoebe Bridgers', genres: ['indie rock', 'indie folk'], popularity: 82, weight: 0.75 },
    { id: 'fleet-foxes', name: 'Fleet Foxes', genres: ['indie folk', 'folk'], popularity: 72, weight: 0.7 },
    { id: 'sufjan-stevens', name: 'Sufjan Stevens', genres: ['folk', 'indie folk'], popularity: 75, weight: 0.65 },
    { id: 'iron-wine', name: 'Iron & Wine', genres: ['folk', 'indie folk'], popularity: 70, weight: 0.6 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['folk', 'indie rock'],
    longTermGenres: ['folk', 'indie rock'],
    driftScore: 0,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 5 — Non-Western dominant: Bollywood + Afrobeats
// ──────────────────────────────────────────────────────────────────────
const p5: PersonaDefinition = {
  id: makeId('bollywood-afrobeats'),
  label: 'Bollywood & Afrobeats',
  description:
    'Home territory rooted outside English-language Western pop. Bollywood, Hindustani classical, and Afrobeats as dominant listening.',
  homeTerritory: {
    genres: ['bollywood', 'hindustani', 'qawwali', 'afrobeats', 'highlife'],
    primaryGenre: 'bollywood',
    country: 'IN',
  },
  coldStart: false,
  seedArtists: [
    { name: 'A.R. Rahman', genres: ['bollywood', 'hindustani'], popularity: 82 },
    { name: 'Lata Mangeshkar', genres: ['bollywood', 'hindustani'], popularity: 85 },
    { name: 'Burna Boy', genres: ['afrobeats', 'afropop'], popularity: 90 },
    { name: 'Wizkid', genres: ['afrobeats', 'afropop'], popularity: 88 },
    { name: 'Nusrat Fateh Ali Khan', genres: ['qawwali', 'world'], popularity: 75 },
  ],
  exploredArtists: [
    { id: 'ar-rahman', name: 'A.R. Rahman', genres: ['bollywood', 'hindustani'], popularity: 82, weight: 0.95 },
    { id: 'lata-mangeshkar', name: 'Lata Mangeshkar', genres: ['bollywood', 'hindustani'], popularity: 85, weight: 0.92 },
    { id: 'burna-boy', name: 'Burna Boy', genres: ['afrobeats', 'afropop'], popularity: 90, weight: 0.9 },
    { id: 'wizkid', name: 'Wizkid', genres: ['afrobeats', 'afropop'], popularity: 88, weight: 0.88 },
    { id: 'nusrat-fateh-ali-khan', name: 'Nusrat Fateh Ali Khan', genres: ['qawwali', 'world'], popularity: 75, weight: 0.85 },
    { id: 'kishore-kumar', name: 'Kishore Kumar', genres: ['bollywood', 'hindustani'], popularity: 80, weight: 0.82 },
    { id: 'kishori-amonkar', name: 'Kishori Amonkar', genres: ['hindustani classical'], popularity: 55, weight: 0.78 },
    { id: 'kavita-krishnamurthy', name: 'Kavita Krishnamurthy', genres: ['bollywood'], popularity: 72, weight: 0.75 },
    { id: 'adekunle-gold', name: 'Adekunle Gold', genres: ['afrobeats', 'afropop'], popularity: 80, weight: 0.78 },
    { id: 'rema', name: 'Rema', genres: ['afrobeats', 'afropop'], popularity: 85, weight: 0.82 },
    { id: 'asake', name: 'Asake', genres: ['afrobeats', 'amapiano'], popularity: 82, weight: 0.8 },
    { id: 'tiwa-savage', name: 'Tiwa Savage', genres: ['afrobeats', 'afropop'], popularity: 78, weight: 0.72 },
    { id: 'davido', name: 'Davido', genres: ['afrobeats', 'afropop'], popularity: 82, weight: 0.75 },
    { id: 'allah-rakha', name: 'Rahat Fateh Ali Khan', genres: ['qawwali', 'bollywood'], popularity: 78, weight: 0.72 },
    { id: 'udit-narayan', name: 'Udit Narayan', genres: ['bollywood', 'hindustani'], popularity: 78, weight: 0.7 },
    { id: 'sonu-nigam', name: 'Sonu Nigam', genres: ['bollywood', 'hindustani'], popularity: 76, weight: 0.68 },
    { id: 'shreya-ghoshal', name: 'Shreya Ghoshal', genres: ['bollywood', 'hindustani'], popularity: 80, weight: 0.72 },
    { id: 'krishna-das', name: 'Krishna Das', genres: ['kirtan', 'world'], popularity: 58, weight: 0.55 },
    { id: 'mdou-moctar', name: 'Mdou Moctar', genres: ['tuareg', 'world'], popularity: 55, weight: 0.5 },
    { id: 'fela-kuti', name: 'Fela Kuti', genres: ['afrobeat', 'highlife'], popularity: 72, weight: 0.65 },
    { id: 'king-sunny-ade', name: 'King Sunny Ade', genres: ['jùjú', 'highlife'], popularity: 62, weight: 0.55 },
    { id: 'angelique-kidjo', name: 'Angelique Kidjo', genres: ['afropop', 'world'], popularity: 72, weight: 0.6 },
    { id: 'mr-eazi', name: 'Mr Eazi', genres: ['afrobeats', 'afropop'], popularity: 75, weight: 0.62 },
    { id: 'tiwa-savage-2', name: 'Yemi Alade', genres: ['afrobeats', 'afropop'], popularity: 72, weight: 0.58 },
    { id: 'sona-mohapatra', name: 'Sona Mohapatra', genres: ['bollywood', 'indie'], popularity: 58, weight: 0.48 },
    { id: 'divine', name: 'Divine', genres: ['desi hip hop', 'bollywood'], popularity: 68, weight: 0.52 },
    { id: 'massive-attack', name: 'Massive Attack', genres: ['trip hop', 'electronic'], popularity: 75, weight: 0.45 },
    { id: 'diljit-dosanjh', name: 'Diljit Dosanjh', genres: ['bollywood', 'punjabi pop'], popularity: 82, weight: 0.65 },
    { id: 'badshah', name: 'Badshah', genres: ['bollywood', 'desi hip hop'], popularity: 80, weight: 0.6 },
    { id: 'pta-sagan', name: 'Pata Sagan', genres: ['highlife', 'afrobeat'], popularity: 45, weight: 0.42 },
    { id: 'ebi', name: 'Ebi', genres: ['persian pop', 'world'], popularity: 60, weight: 0.45 },
    { id: 'goat', name: 'GOAT', genres: ['tuareg', 'world'], popularity: 48, weight: 0.4 },
    { id: 'baaba-maal', name: 'Baaba Maal', genres: ['mbalax', 'world'], popularity: 58, weight: 0.48 },
    { id: 'tamer-vehi', name: 'Tamerlan Alena', genres: ['bollywood', 'hindustani'], popularity: 42, weight: 0.38 },
    { id: 'sukhwinder-singh', name: 'Sukhwinder Singh', genres: ['bollywood'], popularity: 68, weight: 0.52 },
    { id: 'kailash-kher', name: 'Kailash Kher', genres: ['bollywood', 'sufi'], popularity: 65, weight: 0.5 },
    { id: 'tems', name: 'Tems', genres: ['afrobeats', 'rnb'], popularity: 85, weight: 0.72 },
    { id: 'CKay', name: 'CKay', genres: ['afrobeats', 'afropop'], popularity: 78, weight: 0.6 },
    { id: 'fireboy-dml', name: 'Fireboy DML', genres: ['afrobeats', 'afropop'], popularity: 76, weight: 0.58 },
    { id: 'ayra-star', name: 'Ayra Starr', genres: ['afrobeats', 'afropop'], popularity: 78, weight: 0.6 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['bollywood', 'afrobeats', 'qawwali'],
    longTermGenres: ['bollywood', 'hindustani', 'qawwali', 'afrobeats', 'highlife'],
    driftScore: 0.15,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 6 — Already-wide explorer
// ──────────────────────────────────────────────────────────────────────
const p6: PersonaDefinition = {
  id: makeId('wide-explorer'),
  label: 'Wide Explorer',
  description:
    'History shows extensive genre-hopping across 20+ genres. Tests whether system can find genuinely new.',
  homeTerritory: {
    genres: [
      'jazz', 'electronic', 'rock', 'hip hop', 'classical', 'folk', 'ambient',
      'metal', 'rnb', 'reggae', 'latin', 'pop', 'blues', 'soul', 'funk',
      'world', 'experimental', 'drone', 'krautrock', 'post-punk',
    ],
    primaryGenre: 'electronic',
    country: 'US',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Aphex Twin', genres: ['electronic', 'IDM'], popularity: 72 },
    { name: 'Miles Davis', genres: ['jazz'], popularity: 82 },
    { name: 'Radiohead', genres: ['alternative rock', 'electronic'], popularity: 88 },
    { name: 'Fela Kuti', genres: ['afrobeat'], popularity: 72 },
    { name: 'Beethoven', genres: ['classical'], popularity: 90 },
  ],
  exploredArtists: (() => {
    const base: Array<{ id: string; name: string; genres: string[]; popularity: number; weight: number }> = [
      { id: 'aphex-twin', name: 'Aphex Twin', genres: ['electronic', 'IDM'], popularity: 72, weight: 0.9 },
      { id: 'miles-davis', name: 'Miles Davis', genres: ['jazz'], popularity: 82, weight: 0.88 },
      { id: 'radiohead', name: 'Radiohead', genres: ['alternative rock', 'electronic'], popularity: 88, weight: 0.85 },
      { id: 'fela-kuti', name: 'Fela Kuti', genres: ['afrobeat'], popularity: 72, weight: 0.82 },
      { id: 'beethoven', name: 'Beethoven', genres: ['classical'], popularity: 90, weight: 0.8 },
      { id: 'nina-simon', name: 'Nina Simone', genres: ['jazz', 'soul'], popularity: 80, weight: 0.78 },
      { id: 'kraftwerk', name: 'Kraftwerk', genres: ['electronic', 'krautrock'], popularity: 78, weight: 0.75 },
      { id: 'sonic-youth', name: 'Sonic Youth', genres: ['alternative rock', 'noise rock'], popularity: 72, weight: 0.72 },
      { id: 'bob-marley', name: 'Bob Marley', genres: ['reggae'], popularity: 90, weight: 0.7 },
      { id: 'stevie-wonder', name: 'Stevie Wonder', genres: ['soul', 'funk'], popularity: 88, weight: 0.72 },
      { id: 'bach', name: 'J.S. Bach', genres: ['classical', 'baroque'], popularity: 85, weight: 0.65 },
      { id: 'bowie', name: 'David Bowie', genres: ['art rock', 'glam rock'], popularity: 90, weight: 0.78 },
      { id: 'nwa', name: 'N.W.A.', genres: ['hip hop', 'gangsta rap'], popularity: 85, weight: 0.7 },
      { id: 'mbaqanga', name: 'Mahlathini', genres: ['mbaqanga', 'world'], popularity: 45, weight: 0.55 },
      { id: 'tanita-tikaram', name: 'Tanita Tikaram', genres: ['folk', 'singer-songwriter'], popularity: 65, weight: 0.52 },
      { id: 'tortoise', name: 'Tortoise', genres: ['post-rock', 'experimental'], popularity: 60, weight: 0.58 },
      { id: 'can', name: 'Can', genres: ['krautrock', 'experimental'], popularity: 68, weight: 0.62 },
      { id: 'drexciya', name: 'Drexciya', genres: ['electro', 'electronic'], popularity: 52, weight: 0.55 },
      { id: 'sunn-o', name: 'Sunn O)))', genres: ['drone', 'metal'], popularity: 58, weight: 0.5 },
      { id: 'afri-framba', name: 'Afri Framba', genres: ['highlife', 'world'], popularity: 42, weight: 0.45 },
      { id: 'bill-evans', name: 'Bill Evans', genres: ['jazz', 'cool jazz'], popularity: 75, weight: 0.65 },
      { id: 'my-bloody-valentine', name: 'My Bloody Valentine', genres: ['shoegaze', 'alternative rock'], popularity: 68, weight: 0.6 },
      { id: 'black-sabbath', name: 'Black Sabbath', genres: ['metal', 'heavy metal'], popularity: 85, weight: 0.68 },
      { id: 'al-green', name: 'Al Green', genres: ['soul', 'funk'], popularity: 78, weight: 0.62 },
      { id: 'tres-trillitos', name: 'Los Tres Trillitos', genres: ['ranchera', 'latin'], popularity: 38, weight: 0.4 },
      { id: 'neu', name: 'Neu!', genres: ['krautrock', 'experimental'], popularity: 58, weight: 0.55 },
      { id: 'pharoah-sanders', name: 'Pharoah Sanders', genres: ['jazz', 'spiritual jazz'], popularity: 65, weight: 0.6 },
      { id: 'dead-kennedys', name: 'Dead Kennedys', genres: ['punk', 'hardcore punk'], popularity: 72, weight: 0.58 },
      { id: 'sun-ra', name: 'Sun Ra', genres: ['jazz', 'free jazz'], popularity: 62, weight: 0.55 },
      { id: 'pauline-oliveros', name: 'Pauline Oliveros', genres: ['experimental', 'ambient'], popularity: 42, weight: 0.42 },
      { id: 'james-brown', name: 'James Brown', genres: ['funk', 'soul'], popularity: 90, weight: 0.72 },
      { id: 'dizzy-gillespie', name: 'Dizzy Gillespie', genres: ['jazz', 'bebop'], popularity: 75, weight: 0.62 },
      { id: 'the-slits', name: 'The Slits', genres: ['post-punk', 'punk'], popularity: 55, weight: 0.48 },
      { id: 'can-cjk', name: 'Damaged Bug', genres: ['experimental', 'synth'], popularity: 38, weight: 0.38 },
      { id: 'sly-stone', name: 'Sly & the Family Stone', genres: ['funk', 'soul'], popularity: 80, weight: 0.65 },
      { id: 'kali-malho', name: 'Caetano Veloso', genres: ['tropicália', 'world'], popularity: 68, weight: 0.55 },
      { id: 'brian-jonestown', name: 'Brian Jonestown Massacre', genres: ['psychedelic rock', 'shoegaze'], popularity: 58, weight: 0.48 },
      { id: 'lonnie-liston', name: 'Lonnie Liston Smith', genres: ['jazz', 'funk'], popularity: 55, weight: 0.5 },
      { id: 'spacemen3', name: 'Spacemen 3', genres: ['psychedelic rock', 'shoegaze'], popularity: 55, weight: 0.48 },
      { id: 'eris-drew', name: 'Eris Drew', genres: ['house', 'electronic'], popularity: 48, weight: 0.42 },
      { id: 'r-rings', name: 'Rings Around the World', genres: ['electronic', 'experimental'], popularity: 42, weight: 0.38 },
      { id: 'grateful-dead', name: 'Grateful Dead', genres: ['psychedelic rock', 'folk rock'], popularity: 82, weight: 0.6 },
      { id: 'sonic-red-youth', name: 'A Certain Ratio', genres: ['post-punk', 'funk'], popularity: 52, weight: 0.45 },
      { id: 'sade', name: 'Sade', genres: ['soul', 'smooth jazz'], popularity: 85, weight: 0.62 },
      { id: 'sunn-o-)))', name: 'Earth', genres: ['drone', 'metal'], popularity: 52, weight: 0.45 },
      { id: 'tony-joe-white', name: 'Tony Joe White', genres: ['swamp rock', 'soul'], popularity: 55, weight: 0.42 },
      { id: 'lali-puna', name: 'Lali Puna', genres: ['electronic', 'indie'], popularity: 42, weight: 0.38 },
      { id: 'grouper-2', name: 'Grouper', genres: ['ambient', 'dream pop'], popularity: 55, weight: 0.48 },
      { id: 'brian-eno', name: 'Brian Eno', genres: ['ambient', 'electronic'], popularity: 75, weight: 0.7 },
      { id: 'can-adj-2', name: 'Cluster', genres: ['krautrock', 'electronic'], popularity: 50, weight: 0.45 },
      { id: 'om', name: 'Om', genres: ['drone', 'metal'], popularity: 48, weight: 0.42 },
      { id: 'lou-reed', name: 'Lou Reed', genres: ['art rock', 'experimental'], popularity: 78, weight: 0.6 },
      { id: 'velvet-underground', name: 'The Velvet Underground', genres: ['art rock', 'experimental'], popularity: 82, weight: 0.68 },
      { id: 'pharoah-sndrs-2', name: 'Alice Coltrane', genres: ['jazz', 'spiritual jazz'], popularity: 62, weight: 0.58 },
      { id: 'bobby-womack', name: 'Bobby Womack', genres: ['soul', 'funk'], popularity: 68, weight: 0.52 },
      { id: 'david-manners', name: 'David Manners', genres: ['folk', 'experimental'], popularity: 35, weight: 0.35 },
      { id: 'sly-stone-2', name: 'War', genres: ['funk', 'world'], popularity: 68, weight: 0.48 },
      { id: 'can-adj-3', name: 'Popol Vuh', genres: ['krautrock', 'ambient'], popularity: 48, weight: 0.42 },
      { id: 'james-chance', name: 'James Chance', genres: ['no wave', 'punk'], popularity: 48, weight: 0.42 },
      { id: 'arthur-russell', name: 'Arthur Russell', genres: ['experimental', 'folk'], popularity: 52, weight: 0.48 },
      { id: 'lou-reed-2', name: 'John Cale', genres: ['art rock', 'experimental'], popularity: 62, weight: 0.5 },
      { id: 'sun-ara', name: 'Sun Ra', genres: ['jazz', 'free jazz'], popularity: 62, weight: 0.52 },
      { id: 'os-mutantes', name: 'Os Mutantes', genres: ['tropicália', 'psychedelic rock'], popularity: 55, weight: 0.45 },
      { id: 'claude-vonstroke', name: 'Claude VonStroke', genres: ['house', 'electronic'], popularity: 58, weight: 0.42 },
      { id: 'jackson-5', name: 'Jackson 5', genres: ['pop', 'soul'], popularity: 88, weight: 0.55 },
      { id: 'minnie-ripton', name: 'Minnie Riperton', genres: ['soul', 'pop'], popularity: 72, weight: 0.52 },
      { id: 'mohammad-rabia', name: 'Rabih Abou-Khalil', genres: ['world', 'jazz'], popularity: 42, weight: 0.38 },
      { id: 'roky-erickson', name: 'Roky Erickson', genres: ['psychedelic rock', 'punk'], popularity: 55, weight: 0.42 },
      { id: 'bobby-hutcherson', name: 'Bobby Hutcherson', genres: ['jazz', 'hard bop'], popularity: 55, weight: 0.45 },
      { id: 'hailu-mergia', name: 'Hailu Mergia', genres: ['ethio-jazz', 'world'], popularity: 48, weight: 0.42 },
      { id: 'steve-roach', name: 'Steve Roach', genres: ['ambient', 'drone'], popularity: 45, weight: 0.38 },
      { id: 'sly-stone-3', name: 'Mandrill', genres: ['funk', 'soul'], popularity: 48, weight: 0.4 },
      { id: 'can-adj-4', name: 'Ash Ra Tempel', genres: ['krautrock', 'psychedelic'], popularity: 45, weight: 0.4 },
      { id: 'yoko-ono', name: 'Yoko Ono', genres: ['experimental', 'avant-garde'], popularity: 55, weight: 0.42 },
      { id: 'sun-ra-3', name: 'Marzetta', genres: ['jazz', 'free jazz'], popularity: 35, weight: 0.35 },
      { id: 'can-adj-5', name: 'Harmonia', genres: ['krautrock', 'electronic'], popularity: 48, weight: 0.42 },
      { id: 'lou-reed-3', name: 'Nico', genres: ['art rock', 'experimental'], popularity: 65, weight: 0.48 },
      { id: 'arthur-r-2', name: 'Loren Connors', genres: ['experimental', 'drone'], popularity: 35, weight: 0.35 },
      { id: 'sly-4', name: "Mother's Finest", genres: ['funk', 'rock'], popularity: 48, weight: 0.38 },
    ];
    return base;
  })(),
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['ambient', 'experimental', 'spiritual jazz'],
    longTermGenres: [
      'jazz', 'electronic', 'rock', 'hip hop', 'classical', 'folk', 'ambient',
      'metal', 'rnb', 'reggae', 'latin', 'pop', 'blues', 'soul', 'funk',
    ],
    driftScore: 0.5,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 7 — Narrow and resistant (death metal)
// ──────────────────────────────────────────────────────────────────────
const p7: PersonaDefinition = {
  id: makeId('narrow-death-metal'),
  label: 'Narrow Death Metal',
  description:
    'Long history, very tight genre range (death metal only). Low engagement with anything outside.',
  homeTerritory: {
    genres: ['death metal', 'technical death metal', 'brutal death metal'],
    primaryGenre: 'death metal',
    country: 'US',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Death', genres: ['death metal'], popularity: 72 },
    { name: 'Morbid Angel', genres: ['death metal'], popularity: 68 },
    { name: 'Obituary', genres: ['death metal'], popularity: 65 },
    { name: 'Cannibal Corpse', genres: ['brutal death metal'], popularity: 70 },
    { name: 'Napalm Death', genres: ['death metal', 'grindcore'], popularity: 68 },
  ],
  exploredArtists: [
    { id: 'death', name: 'Death', genres: ['death metal'], popularity: 72, weight: 0.95 },
    { id: 'morbid-angel', name: 'Morbid Angel', genres: ['death metal'], popularity: 68, weight: 0.92 },
    { id: 'obituary', name: 'Obituary', genres: ['death metal'], popularity: 65, weight: 0.9 },
    { id: 'cannibal-corpse', name: 'Cannibal Corpse', genres: ['brutal death metal'], popularity: 70, weight: 0.88 },
    { id: 'napalm-death', name: 'Napalm Death', genres: ['death metal', 'grindcore'], popularity: 68, weight: 0.85 },
    { id: 'deicide', name: 'Deicide', genres: ['death metal'], popularity: 62, weight: 0.82 },
    { id: 'atheist', name: 'Atheist', genres: ['technical death metal'], popularity: 58, weight: 0.8 },
    { id: 'cynic', name: 'Cynic', genres: ['technical death metal'], popularity: 55, weight: 0.78 },
    { id: 'suffocation', name: 'Suffocation', genres: ['brutal death metal'], popularity: 62, weight: 0.75 },
    { id: 'immolation', name: 'Immolation', genres: ['death metal'], popularity: 58, weight: 0.72 },
    { id: 'grave', name: 'Grave', genres: ['death metal'], popularity: 52, weight: 0.7 },
    { id: 'dismember', name: 'Dismember', genres: ['death metal'], popularity: 55, weight: 0.68 },
    { id: 'entombed', name: 'Entombed', genres: ['death metal'], popularity: 62, weight: 0.72 },
    { id: 'autopsy', name: 'Autopsy', genres: ['death metal'], popularity: 55, weight: 0.65 },
    { id: 'bolt-thrower', name: 'Bolt Thrower', genres: ['death metal', 'grindcore'], popularity: 60, weight: 0.68 },
    { id: 'monstrosity', name: 'Monstrosity', genres: ['technical death metal'], popularity: 48, weight: 0.62 },
    { id: 'spawn-of-possession', name: 'Spawn of Possession', genres: ['technical death metal'], popularity: 42, weight: 0.58 },
    { id: 'nile', name: 'Nile', genres: ['technical death metal'], popularity: 58, weight: 0.7 },
    { id: 'behemoth', name: 'Behemoth', genres: ['death metal', 'blackened death metal'], popularity: 72, weight: 0.72 },
    { id: 'dyscord', name: 'Discord', genres: ['death metal'], popularity: 38, weight: 0.52 },
    { id: 'vomitory', name: 'Vomitory', genres: ['brutal death metal'], popularity: 40, weight: 0.55 },
    { id: 'benighted', name: 'Benighted', genres: ['brutal death metal'], popularity: 45, weight: 0.52 },
    { id: 'hour-of-penance', name: 'Hour of Penance', genres: ['technical death metal'], popularity: 48, weight: 0.55 },
    { id: ' Fleshgod Apocalypse', name: 'Fleshgod Apocalypse', genres: ['technical death metal'], popularity: 55, weight: 0.58 },
    { id: 'ex-deo', name: 'Ex Deo', genres: ['death metal'], popularity: 42, weight: 0.48 },
    { id: 'abysmal-dawn', name: 'Abysmal Dawn', genres: ['death metal'], popularity: 40, weight: 0.48 },
    { id: 'vital-remains', name: 'Vital Remains', genres: ['death metal'], popularity: 42, weight: 0.5 },
    { id: 'broken Hope', name: 'Broken Hope', genres: ['brutal death metal'], popularity: 40, weight: 0.48 },
    { id: 'beneath-the-massacre', name: 'Beneath the Massacre', genres: ['technical death metal'], popularity: 42, weight: 0.5 },
    { id: 'the-faceless', name: 'The Faceless', genres: ['technical death metal'], popularity: 48, weight: 0.52 },
    { id: 'revocation', name: 'Revocation', genres: ['technical death metal', 'thrash metal'], popularity: 52, weight: 0.55 },
    { id: 'gorod', name: 'Gorod', genres: ['technical death metal'], popularity: 45, weight: 0.5 },
    { id: 'nyogthaeblisz', name: 'Nyogothaeblisz', genres: ['blackened death metal'], popularity: 35, weight: 0.42 },
    { id: 'blasphemy', name: 'Blasphemy', genres: ['blackened death metal'], popularity: 48, weight: 0.45 },
    { id: 'archaic', name: 'Archaic', genres: ['death metal'], popularity: 38, weight: 0.42 },
    { id: 'septic-flesh', name: 'Septicflesh', genres: ['symphonic death metal'], popularity: 55, weight: 0.52 },
    { id: 'existentia', name: 'Existentia', genres: ['death metal'], popularity: 32, weight: 0.38 },
    { id: 'phobic', name: 'Phobic', genres: ['brutal death metal'], popularity: 30, weight: 0.35 },
    { id: 'putrid-offering', name: 'Putrid Offering', genres: ['death metal'], popularity: 28, weight: 0.32 },
    { id: 'infernal-td', name: 'Infernal Tenement', genres: ['death metal'], popularity: 30, weight: 0.35 },
    { id: 'sarcasm-td', name: 'Sarcasm', genres: ['death metal'], popularity: 35, weight: 0.38 },
    { id: 'gravatech', name: 'Gravatech', genres: ['technical death metal'], popularity: 28, weight: 0.32 },
    { id: 'morbid-angel-2', name: 'Massacre', genres: ['death metal'], popularity: 48, weight: 0.52 },
    { id: 'gruesome', name: 'Gruesome', genres: ['death metal'], popularity: 42, weight: 0.48 },
    { id: 'master', name: 'Master', genres: ['death metal'], popularity: 45, weight: 0.5 },
    { id: 'pestilence', name: 'Pestilence', genres: ['technical death metal'], popularity: 52, weight: 0.55 },
    { id: 'asphyx', name: 'Asphyx', genres: ['death metal'], popularity: 55, weight: 0.55 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['death metal', 'technical death metal'],
    longTermGenres: ['death metal', 'technical death metal', 'brutal death metal'],
    driftScore: 0.02,
  },
};

// ──────────────────────────────────────────────────────────────────────
// Persona 8 — Different niche: Lo-fi / Ambient / Shoegaze
// ──────────────────────────────────────────────────────────────────────
const p8: PersonaDefinition = {
  id: makeId('lofi-ambient'),
  label: 'Lo-fi Ambient',
  description:
    'Deep in ambient, lo-fi, and shoegaze. Used specifically for cross-persona overlap check with persona 2.',
  homeTerritory: {
    genres: ['ambient', 'lo-fi', 'shoegaze', 'downtempo', 'dream pop'],
    primaryGenre: 'ambient',
    country: 'GB',
  },
  coldStart: false,
  seedArtists: [
    { name: 'Brian Eno', genres: ['ambient', 'electronic'], popularity: 75 },
    { name: 'My Bloody Valentine', genres: ['shoegaze', 'alternative rock'], popularity: 68 },
    { name: 'Tycho', genres: ['ambient', 'electronic'], popularity: 68 },
    { name: 'Boards of Canada', genres: ['electronic', 'ambient'], popularity: 68 },
    { name: 'C418', genres: ['ambient', 'lo-fi'], popularity: 65 },
  ],
  exploredArtists: [
    { id: 'brian-eno', name: 'Brian Eno', genres: ['ambient', 'electronic'], popularity: 75, weight: 0.95 },
    { id: 'my-bloody-valentine', name: 'My Bloody Valentine', genres: ['shoegaze', 'alternative rock'], popularity: 68, weight: 0.9 },
    { id: 'tycho', name: 'Tycho', genres: ['ambient', 'electronic'], popularity: 68, weight: 0.88 },
    { id: 'boards-of-canada', name: 'Boards of Canada', genres: ['electronic', 'ambient'], popularity: 68, weight: 0.92 },
    { id: 'c418', name: 'C418', genres: ['ambient', 'lo-fi'], popularity: 65, weight: 0.85 },
    { id: 'stars-of-the-lid', name: 'Stars of the Lid', genres: ['ambient', 'drone'], popularity: 55, weight: 0.82 },
    { id: 'grouper', name: 'Grouper', genres: ['ambient', 'dream pop'], popularity: 55, weight: 0.8 },
    { id: 'slowdive', name: 'Slowdive', genres: ['shoegaze', 'dream pop'], popularity: 68, weight: 0.85 },
    { id: 'cocteau-twins', name: 'Cocteau Twins', genres: ['shoegaze', 'dream pop'], popularity: 65, weight: 0.78 },
    { id: 'aphex-twin', name: 'Aphex Twin', genres: ['electronic', 'ambient'], popularity: 72, weight: 0.72 },
    { id: 'gas', name: 'Gas', genres: ['ambient', 'electronic'], popularity: 48, weight: 0.75 },
    { id: 'tim-hecker', name: 'Tim Hecker', genres: ['ambient', 'drone'], popularity: 50, weight: 0.72 },
    { id: 'william-basinski', name: 'William Basinski', genres: ['ambient', 'drone'], popularity: 45, weight: 0.7 },
    { id: 'helios', name: 'Helios', genres: ['ambient', 'electronic'], popularity: 50, weight: 0.68 },
    { id: 'helios-2', name: 'Koda', genres: ['ambient', 'electronic'], popularity: 48, weight: 0.65 },
    { id: 'loscil', name: 'Loscil', genres: ['ambient', 'electronic'], popularity: 48, weight: 0.62 },
    { id: 'burial', name: 'Burial', genres: ['dubstep', 'ambient', 'garage'], popularity: 72, weight: 0.72 },
    { id: 'jamie-xx', name: 'Jamie xx', genres: ['electronic', 'garage'], popularity: 75, weight: 0.65 },
    { id: 'four-tet', name: 'Four Tet', genres: ['electronic', 'ambient'], popularity: 72, weight: 0.68 },
    { id: 'ride', name: 'Ride', genres: ['shoegaze', 'alternative rock'], popularity: 60, weight: 0.65 },
    { id: 'lush', name: 'Lush', genres: ['shoegaze', 'alternative rock'], popularity: 55, weight: 0.62 },
    { id: 'chapterhouse', name: 'Chapterhouse', genres: ['shoegaze'], popularity: 42, weight: 0.55 },
    { id: 'lush-2', name: 'Ringo Deathstarr', genres: ['shoegaze'], popularity: 42, weight: 0.52 },
    { id: 'lush-3', name: 'Nothing', genres: ['shoegaze', 'alternative rock'], popularity: 48, weight: 0.5 },
    { id: 'deerhunter', name: 'Deerhunter', genres: ['shoegaze', 'indie rock'], popularity: 58, weight: 0.55 },
    { id: 'beach-house', name: 'Beach House', genres: ['dream pop', 'indie'], popularity: 68, weight: 0.62 },
    { id: 'wild-nothing', name: 'Wild Nothing', genres: ['dream pop', 'indie'], popularity: 52, weight: 0.52 },
    { id: 'diiv', name: 'DIIV', genres: ['shoegaze', 'dream pop'], popularity: 55, weight: 0.55 },
    { id: 'men-i-trust', name: 'Men I Trust', genres: ['dream pop', 'indie'], popularity: 60, weight: 0.52 },
    { id: 'sunset-villa', name: 'Tycho', genres: ['ambient', 'electronic'], popularity: 68, weight: 0.6 },
    { id: 'helios-3', name: 'Emancipator', genres: ['ambient', 'electronic'], popularity: 55, weight: 0.52 },
    { id: 'helios-4', name: 'Nils Frahm', genres: ['ambient', 'neoclassical'], popularity: 68, weight: 0.58 },
    { id: 'olafur', name: 'Olafur Arnalds', genres: ['ambient', 'neoclassical'], popularity: 68, weight: 0.55 },
    { id: 'johann-johannsson', name: 'Johann Johannsson', genres: ['ambient', 'neoclassical'], popularity: 60, weight: 0.52 },
    { id: 'max-richter', name: 'Max Richter', genres: ['ambient', 'neoclassical'], popularity: 72, weight: 0.58 },
    { id: 'hammock', name: 'Hammock', genres: ['ambient', 'post-rock'], popularity: 48, weight: 0.5 },
    { id: 'agua-de-annique', name: 'Agua de Annique', genres: ['dream pop', 'indie'], popularity: 42, weight: 0.42 },
    { id: 'low-hum', name: 'Low Hum', genres: ['shoegaze', 'ambient'], popularity: 38, weight: 0.42 },
    { id: 'lush-4', name: 'Beaches', genres: ['shoegaze', 'noise rock'], popularity: 38, weight: 0.4 },
    { id: 'shazam-island', name: 'Shazam', genres: ['shoegaze', 'indie'], popularity: 35, weight: 0.38 },
    { id: 'lush-5', name: 'Kinoko Teikoku', genres: ['shoegaze', 'indie'], popularity: 45, weight: 0.42 },
    { id: 'helios-5', name: 'A Winged Victory for the Sullen', genres: ['ambient', 'drone'], popularity: 48, weight: 0.48 },
    { id: 'robert-rich', name: 'Robert Rich', genres: ['ambient', 'electronic'], popularity: 42, weight: 0.45 },
    { id: 'scott-walker', name: 'Scott Walker', genres: ['experimental', 'ambient'], popularity: 58, weight: 0.48 },
    { id: 'arthur-r-3', name: 'Juliana Barwick', genres: ['ambient', 'experimental'], popularity: 45, weight: 0.45 },
    { id: 'helios-6', name: 'Pausal', genres: ['ambient', 'drone'], popularity: 35, weight: 0.38 },
    { id: 'lush-6', name: 'The Radio Dept.', genres: ['shoegaze', 'indie pop'], popularity: 50, weight: 0.48 },
    { id: 'lush-7', name: 'Tennis', genres: ['dream pop', 'indie pop'], popularity: 50, weight: 0.42 },
  ],
  listeningHistory: [],
  tasteDrift: {
    recentGenres: ['ambient', 'lo-fi', 'shoegaze'],
    longTermGenres: ['ambient', 'lo-fi', 'shoegaze', 'downtempo', 'dream pop'],
    driftScore: 0.05,
  },
};

// ─── Canonical representative lists (for genericness check) ───────────

/** Most-famous, most-training-data-dense representative per scene. */
export const CANONICAL_REPRESENTATIVES: Record<string, string[]> = {
  dubstep: ['Burial', 'Skream', 'Benga', 'Digital Mystikz'],
  'uk garage': ['MJ Cole', 'Artful Dodger', 'Craig David'],
  grime: ['Wiley', 'Dizzee Rascal', 'Skepta'],
  'bass music': ['Burial', 'Kode9', 'Skream'],
  bollywood: ['A.R. Rahman', 'Lata Mangeshkar', 'Kishore Kumar', 'S.D. Burman'],
  hindustani: ['Ravi Shankar', 'Zakir Hussain', 'Kishori Amonkar'],
  qawwali: ['Nusrat Fateh Ali Khan', 'Rahat Fateh Ali Khan', 'Abida Parveen'],
  afrobeats: ['Burna Boy', 'Wizkid', 'Davido', 'Tiwa Savage'],
  highlife: ['Fela Kuti', 'King Sunny Ade', 'E.T. Mensah'],
  ambient: ['Brian Eno', 'Harold Budd', 'Stars of the Lid'],
  shoegaze: ['My Bloody Valentine', 'Slowdive', 'Cocteau Twins'],
  'lo-fi': ['Nujabes', 'J Dilla', 'C418'],
  'dream pop': ['Beach House', 'Cocteau Twins', 'Beach Fossils'],
  'death metal': ['Death', 'Morbid Angel', 'Cannibal Corpse', 'Obituary'],
  'technical death metal': ['Cynic', 'Atheist', 'Nile', 'Suffocation'],
  'folk': ['Bob Dylan', 'Nick Drake', 'Joni Mitchell'],
  'indie folk': ['Bon Iver', 'Iron & Wine', 'Fleet Foxes'],
  pop: ['Taylor Swift', 'Ed Sheeran', 'Adele', 'Beyonce'],
  'k-pop': ['BTS', 'BLACKPINK', 'TWICE', 'EXO'],
};

// ─── Export all personas ──────────────────────────────────────────────

export const PERSONAS: PersonaDefinition[] = [
  p1, p2, p3, p4, p5, p6, p7, p8,
];
